// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	repository "api-gmr/store/repository"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Payment is an autogenerated mock type for the Payment type
type Payment struct {
	mock.Mock
}

// All provides a mock function with given fields: ctx
func (_m *Payment) All(ctx context.Context) ([]repository.PaymentModel, error) {
	ret := _m.Called(ctx)

	var r0 []repository.PaymentModel
	if rf, ok := ret.Get(0).(func(context.Context) []repository.PaymentModel); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.PaymentModel)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
