// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	model "api-gmr/model"

	mock "github.com/stretchr/testify/mock"
)

// IAuthService is an autogenerated mock type for the IAuthService type
type IAuthService struct {
	mock.Mock
}

// CreateToken provides a mock function with given fields: user
func (_m *IAuthService) CreateToken(user model.User) (string, error) {
	ret := _m.Called(user)

	var r0 string
	if rf, ok := ret.Get(0).(func(model.User) string); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Validate provides a mock function with given fields: user
func (_m *IAuthService) Validate(user model.UserLogin) (model.User, error) {
	ret := _m.Called(user)

	var r0 model.User
	if rf, ok := ret.Get(0).(func(model.UserLogin) model.User); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.UserLogin) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
